---
title: "Lab6"
subtitle: "Exercises"
author: "Irimie Fabio"
output: 
  pdf_document:
    toc: true
    keep_tex: true 
---

# Exercise 1

## A
Compare the PDF's and the CDF's of the following Uniform continuous
random variables (hint: see page 3 of the slides).

Calculate:
1. $X1 \sim U(0,1)$
```{r}
a <- 0
b <- 1
seq <- seq(a-0.5,b+0.5,0.01)
x1 <- data.frame(
         x = seq,
         pdf = dunif(seq,a,b),
         cdf = punif(seq,a,b)
)
```
2. $X2 \sim U(-3,2)$
```{r}
a <- -3
b <- 2
seq <- seq(a-0.5,b+0.5,0.01)
x2 <- data.frame(
         x = seq,
         pdf = dunif(seq,a,b),
         cdf = punif(seq,a,b)
)
```
3. $X3 \sim U(2,4)$
```{r}
a <- 2
b <- 4
seq <- seq(a-0.5,b+0.5,0.01)
x3 <- data.frame(
         x = seq,
         pdf = dunif(seq,a,b),
         cdf = punif(seq,a,b)
)
```
4. $X4 \sim U(0.8,2.5)$
```{r}
a <- 0.8 
b <- 2.5 
seq <- seq(a-0.5,b+0.5,0.01)
x4 <- data.frame(
         x = seq,
         pdf = dunif(seq,a,b),
         cdf = punif(seq,a,b)
)
```

## B
Create a new figure with two vertical panels: first row PDFs, second row
CDFs (hint: use the library cowplot and the plot_grid() function to
arrange multiple ggplot objects).
```{r}
library(ggplot2)
library(cowplot)
```
